version: '3'
services:

  fdk-organization-bff:
    build: .
    image: eu.gcr.io/digdir-fdk-infra/fdk-organization-bff:test
    ports:
      - "8080:8080"
    depends_on:
      - wiremock

  wiremock:
    image: rodolpheche/wiremock
    ports:
      - "8000:8080"
    volumes:
      - ./mock_mappings/mappings:/home/wiremock/mappings
