version: "3"
services:
  servicesmock:
    image: rodolpheche/wiremock
    ports:
      - "8080:8080"
    volumes:
      - $MOCK_DIR/mock/mappings:/home/wiremock/mappings
  rabbitmq:
    image: rabbitmq:3.6-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  fdk-organization-bff:
      image: $TEST_IMAGE
      ports:
        - "8000:8000"
      depends_on:
        - servicesmock
      environment:
        - HOST_URL=http://localhost
        - HOST_PORT=8000
        - API_URL=http://servicesmock:8080/