openapi: 3.0.0
info:
  title: fdk-organization-bff
  version: '1.0'
  description: Backend for Frontend service that provides information about organizations and their published content in Felles Datakatalogs
  contact:
    name: Felles Datakatalog
    url: 'https://fellesdatakatalog.digdir.no/'
    email: fellesdatakatalog@digdir.no
  license:
    url: 'http://data.norge.no/nlod/no/2.0'
    name: License of API
servers:
  - url: 'http://organization-bff.data.norge.no'
    description: production
paths:
  /organizationcatalogs:
    get:
      summary: Get all organizations that have published content in Felles Datakatalog.
      tags:
        - organizationcatalogs
      operationId: get_organization_catalogs
      responses:
        '200':
          description: OK. Returns an array of all organizations with published content in Felles Datakatalog.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationCatalogList'
  '/organizationcatalog/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Get detailed data regarding an organization and its published content in Felles Datakatalog.
      tags:
        - ogranizationcatalogs
      operationId: get_organization_catalog
      responses:
        '200':
          description: OK. Returns data regarding an organizations and its published content in Felles Datakatalog.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationCatalog'

components:
  schemas:
    OrganizationCatalog:
      title: OrganizationCatalog
      type: object
      properties:
        organization:
          $ref: '#/components/schemas/OrganizationDetails'
        datasets:
          type: object
          properties:
            total:
              type: integer
            new:
              type: integer
            authoritative:
              type: integer
            open:
              type: integer
            quality:
              $ref: '#/components/schemas/CatalogQualityRating'
    CatalogQualityRating:
      title: CatalogQualityRating
      type: object
      properties:
        category:
          type: string
          enum:
            - excellent
            - good
            - sufficient
            - poor
        percentage:
          type: integer
    OrganizationDetails:
      title: OrganizationDetails
      type: object
      properties:
        name:
          type: string
        organizationId:
          type: string
        prefLabel:
          $ref: '#/components/schemas/LanguageObject'
        orgPath:
          type: string
        orgType:
          type: string
        sectorCode:
          type: string
        industryCode:
          type: string
        homepage:
          type: string
        seeAlso:
          type: string
        icon:
          type: string
    OrganizationCatalogSummary:
      title: OrganizationCatalog
      type: object
      properties:
        organization:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            prefLabel:
              $ref: '#/components/schemas/LanguageObject'
        dataset_count:
          type: integer
        concept_count:
          type: integer
        dataservice_count:
          type: integer
        informationmodel_count:
          type: integer
    OrganizationCatalogList:
      type: object
      properties:
        organizations:
          type: array
          items:
            $ref: '#/components/schemas/OrganizationCatalogSummary'
    LanguageObject:
      title: LanguageObject
      type: object
      properties:
        nb:
          type: string
        nn:
          type: string
        en:
          type: string
        no:
          type: string
