---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-fdk-organization-bff.yaml
  - service-fdk-organization-bff.yaml
images:
  - name: fdk-organization-bff
    newName: ghcr.io/informasjonsforvaltning/fdk-organization-bff
    newTag: $(GIT_COMMIT_SHA)
