---
apiVersion: v1
kind: Service
metadata:
  labels:
    fdk.service: fdk-organization-bff
  name: fdk-organization-bff
spec:
  selector:
    fdk.service: fdk-organization-bff
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
